### ISSUE TITLE
Run automated testing on check-in

### ISSUE THREAD

**Issue by thesheps** [thesheps/plang#2]
We need to decide on a mechanism for unit testing this here code, and amend the .travis.yml configuration to run the tests automatically.

**Comment by john-chapman** [comment]
There are two parts to this:

(1) Integrate gtest with plang_unit. This requires linking the gtest lib; hopefully there will be a way to have travis get/build gtest without us having to commit gtest to the repo.

(2) Have travis run plang_unit after a successful build and do _something_ with the output (e.g. email us with an XML report if it fails).

**Comment by thesheps** [comment]
I think it might be possible to have travis call:
- sudo apt-get install libgtest-dev

http://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/

**Comment by thesheps** [comment]
Following internal discussion we've instead opted to use Catch.  This is now implemented with the CI pipeline, and happily it plays nicely with the mingw toolset. Not sure there's any reason just yet to _do anything_ with the output.  Let's create a new issue for that, and stick it in the backlog for review?
