### ISSUE TITLE
Simple REPL Spike

### ISSUE THREAD

**Issue by thesheps** [thesheps/plang#3]
Perhaps a first spike, simply echoing back to the user?

**Comment by john-chapman** [comment]
This is a good first step as we need plang_go to be vaguely functional as a starting point.
- Launch plang_go, enters 'live mode' by default.
- Console input (which would be sent to the plang interpreter) is echoed directly back to the user.
- Special command to quit (maybe ":q" or ":quit" - the idea being that in the future we can issue special commands to plang_go in this way e.g. ":run myscript.plang).

**Comment by thesheps** [comment]
Agreed, that's a really good idea - plang_go (plango) is essentially the
entry point application.  Would be nice to have this as a candidate for
unit test, too!
